//original author:  Banbury

scene = new Scene()
scene.insertColumn(0)
AI = scene.loadLevel("AI", "F://AI.png")
E = scene.loadLevel("E", "F://E.png")
etc = scene.loadLevel("etc", "F://etc.png")
FV = scene.loadLevel("FV", "F://FV.png")
L = scene.loadLevel("L", "F://L.png")
MBP = scene.loadLevel("MBP", "F://MBP.png")
O = scene.loadLevel("O", "F://O.png")
rest = scene.loadLevel("rest", "F://rest.png")
U = scene.loadLevel("U", "F://U.png")
WQ = scene.loadLevel("WQ", "F://WQ.png")
scene.setCell(0, 0, { level:"etc", fid:'-2' })
scene.setCell(1, 0, { level:"etc", fid:'-2' })
scene.setCell(2, 0, { level:"AI", fid:'-2' })
scene.setCell(3, 0, { level:"AI", fid:'-2' })
scene.setCell(4, 0, { level:"etc", fid:'-2' })
scene.setCell(5, 0, { level:"etc", fid:'-2' })
scene.setCell(6, 0, { level:"etc", fid:'-2' })
scene.setCell(7, 0, { level:"E", fid:'-2' })
scene.setCell(8, 0, { level:"E", fid:'-2' })
//scene.setCell(9, 0, { level:"etc", fid:'-2' })
scene.setCell(10, 0, { level:"etc", fid:'-2' })
scene.setCell(11, 0, { level:"U", fid:'-2' })
scene.setCell(12, 0, { level:"etc", fid:'-2' })
scene.setCell(13, 0, { level:"etc", fid:'-2' })
scene.setCell(14, 0, { level:"E", fid:'-2' })
scene.setCell(15, 0, { level:"etc", fid:'-2' })
scene.setCell(16, 0, { level:"etc", fid:'-2' })
scene.setCell(17, 0, { level:"etc", fid:'-2' })
scene.setCell(18, 0, { level:"etc", fid:'-2' })
scene.setCell(19, 0, { level:"U", fid:'-2' })
scene.setCell(20, 0, { level:"AI", fid:'-2' })